services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: './bin/rails server'
    envVars:
      - key: postgresql://chatgenie:bfXLQFP3s4wz5HMrCwwVlbfzaUY7vtjf@dpg-d3ru1d24d50c73fmbft0-a/chatgenie_q4j2
        fromDatabase:
          name: mysite-db
          property: connectionString
      - key: c14f3a7c81d9db5409eb276e31654346
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
databases:
  - name: mysite-db
    plan: free